### ISSUE TITLE
Interested but needs more docs

### ISSUE THREAD

**Issue by austinrivas** [open-source-labs/spearmint#107]
Hi all,

Really interested in the premise but it is difficult to know where to start.

Some additional documentation and guides would go a long ways towards helping me make a case for adopting this.

I would love to be able to delegate developing tests to our QA team, but as it stands I don't know that I could effectively train anyone to use this while I am not sure how to use it myself.

Best of luck and I will stay tuned for further development.

**Comment by btran140** [comment]
Hi Austin, we were able to implement documentation for each file, as well as adding a user guide on where to start regarding the application! Hopefully. We've also provided a visualization on how each file interacts with each other!
